baseURL = "https://book-review-system.info/"
languageCode = "ru-ru"
title = "Book Review System"
theme = "FixIt"

publishDir = "docs"

[taxonomies]
category = "categories"
tag      = "tags"

buildFuture = true