baseURL = "https://book-review-system.info/"
languageCode = "en-us"
title = "Book Review System"
theme = "Mainroad"

publishDir = "docs"

[pagination]
pagerSize = 10

[taxonomies]
category = "categories"
tag      = "tags"

buildFuture = true